### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/mpii/annot/valid.json'

### ISSUE THREAD

**Issue by c1a1o1** [Microsoft/human-pose-estimation.pytorch#102]
/root/anaconda3/bin/python /home/dell/下载/human-pose-estimation.pytorch-master/pose_estimation/valid.py --cfg ../experiments/mpii/resnet152/256x256_d256x3_adam_lr1e-3.yaml --flip-test --model-file ../models/pytorch/pose_mpii/pose_resnet_152_256x256.pth.tar
=> creating output/mpii/pose_resnet_152/256x256_d256x3_adam_lr1e-3
=> creating log/mpii/pose_resnet_152/256x256_d256x3_adam_lr1e-3_2019-03-20-21-12
Namespace(cfg='../experiments/mpii/resnet152/256x256_d256x3_adam_lr1e-3.yaml', coco_bbox_file=None, flip_test=True, frequent=100, gpus=None, model_file='../models/pytorch/pose_mpii/pose_resnet_152_256x256.pth.tar', post_process=False, shift_heatmap=False, use_detect_bbox=False, workers=None)
{'CUDNN': {'BENCHMARK': True, 'DETERMINISTIC': False, 'ENABLED': True},
 'DATASET': {'DATASET': 'mpii',
             'DATA_FORMAT': 'jpg',
             'FLIP': True,
             'HYBRID_JOINTS_TYPE': '',
             'ROOT': 'data/mpii/',
             'ROT_FACTOR': 30,
             'SCALE_FACTOR': 0.25,
             'SELECT_DATA': False,
             'TEST_SET': 'valid',
             'TRAIN_SET': 'train'},
 'DATA_DIR': '',
 'DEBUG': {'DEBUG': False,
           'SAVE_BATCH_IMAGES_GT': True,
           'SAVE_BATCH_IMAGES_PRED': True,
           'SAVE_HEATMAPS_GT': True,
           'SAVE_HEATMAPS_PRED': True},
 'GPUS': '0',
 'LOG_DIR': 'log',
 'LOSS': {'USE_TARGET_WEIGHT': True},
 'MODEL': {'EXTRA': {'DECONV_WITH_BIAS': False,
                     'FINAL_CONV_KERNEL': 1,
                     'HEATMAP_SIZE': array([64, 64]),
                     'NUM_DECONV_FILTERS': [256, 256, 256],
                     'NUM_DECONV_KERNELS': [4, 4, 4],
                     'NUM_DECONV_LAYERS': 3,
                     'NUM_LAYERS': 152,
                     'SIGMA': 2,
                     'TARGET_TYPE': 'gaussian'},
           'IMAGE_SIZE': array([256, 256]),
           'INIT_WEIGHTS': True,
           'NAME': 'pose_resnet',
           'NUM_JOINTS': 16,
           'PRETRAINED': 'models/pytorch/imagenet/resnet152-b121ed2d.pth',
           'STYLE': 'pytorch'},
 'OUTPUT_DIR': 'output',
 'PRINT_FREQ': 100,
 'TEST': {'BATCH_SIZE': 32,
          'BBOX_THRE': 1.0,
          'COCO_BBOX_FILE': '',
          'FLIP_TEST': True,
          'IMAGE_THRE': 0.0,
          'IN_VIS_THRE': 0.0,
          'MODEL_FILE': '../models/pytorch/pose_mpii/pose_resnet_152_256x256.pth.tar',
          'NMS_THRE': 1.0,
          'OKS_THRE': 0.5,
          'POST_PROCESS': True,
          'SHIFT_HEATMAP': True,
          'USE_GT_BBOX': False},
 'TRAIN': {'BATCH_SIZE': 32,
           'BEGIN_EPOCH': 0,
           'CHECKPOINT': '',
           'END_EPOCH': 140,
           'GAMMA1': 0.99,
           'GAMMA2': 0.0,
           'LR': 0.001,
           'LR_FACTOR': 0.1,
           'LR_STEP': [90, 120],
           'MOMENTUM': 0.9,
           'NESTEROV': False,
           'OPTIMIZER': 'adam',
           'RESUME': False,
           'SHUFFLE': True,
           'WD': 0.0001},
 'WORKERS': 4}
=> loading model from ../models/pytorch/pose_mpii/pose_resnet_152_256x256.pth.tar
/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "/home/dell/下载/human-pose-estimation.pytorch-master/pose_estimation/valid.py", line 165, in <module>
    main()
  File "/home/dell/下载/human-pose-estimation.pytorch-master/pose_estimation/valid.py", line 148, in main
    normalize,
  File "/home/dell/下载/human-pose-estimation.pytorch-master/pose_estimation/../lib/dataset/mpii.py", line 33, in __init__
    self.db = self._get_db()
  File "/home/dell/下载/human-pose-estimation.pytorch-master/pose_estimation/../lib/dataset/mpii.py", line 45, in _get_db
    with open(file_name) as anno_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/mpii/annot/valid.json'

Process finished with exit code 1

**Comment by 738654805** [comment]
@c1a1o1  You should download the valid.json file from the googledrive. just follow the instructions in readme. (需要下载，科学上网)

**Comment by jonewei** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './hps/zerospeech_english.json'
