### ISSUE TITLE
error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by liuchanfeng165** [microsoft/human-pose-estimation.pytorch#112]
Hi ,
Could u help me ?I found some ways to sovle it but failed
=> load 6352 samples
->loss  tensor(0.0014, device='cuda:0', grad_fn=<DivBackward0>)
Traceback (most recent call last):
  File "train.py", line 261, in <module>
    main()
  File "train.py", line 180, in main
    final_output_dir, tb_log_dir, writer_dict)
  File "H:\paper_coding\human-pose-estimation.pytorch-master\lib\core\function.p
y", line 56, in train
    loss.backward( ) # allow_unreachable=True)  #retain_graph=True
  File "E:\Python36\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "E:\Python36\lib\site-packages\torch\autograd\__init__.py", line 93, in b
ackward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

**Comment by liuchanfeng165** [comment]
> Hi ,
> Could u help me ?I found some ways to sovle it but failed
> => load 6352 samples
> ->loss tensor(0.0014, device='cuda:0', grad_fn=)
> Traceback (most recent call last):
> File "train.py", line 261, in 
> main()
> File "train.py", line 180, in main
> final_output_dir, tb_log_dir, writer_dict)
> File "H:\paper_coding\human-pose-estimation.pytorch-master\lib\core\function.p
> y", line 56, in train
> loss.backward( ) # allow_unreachable=True) #retain_graph=True
> File "E:\Python36\lib\site-packages\torch\tensor.py", line 107, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "E:\Python36\lib\site-packages\torch\autograd__init__.py", line 93, in b
> ackward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

version mistake
