### ISSUE TITLE
AttributeError: 'torch._C.Value' object has no attribute 'uniqueName'

### ISSUE THREAD

**Issue by aa349276** [microsoft/human-pose-estimation.pytorch#122]
When I excuted the following cmd
`python3 pose_estimation/train.py     --cfg experiments/mpii/resnet50/256x256_d256x3_adam_lr1e-3.yaml
`
But got error:
`=> loading pretrained model models/pytorch/imagenet/resnet50-19c8e357.pth
Traceback (most recent call last):
  File "pose_estimation/train.py", line 206, in <module>
    main()
  File "pose_estimation/train.py", line 112, in main
    writer_dict['writer'].add_graph(model, (dump_input, ), verbose=False)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 255, in graph
    list_of_nodes, node_stats = parse(graph, args)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 211, in parse
    nodes_py.append(NodePyIO(node, 'input'))
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 63, in __init__
    super(NodePyIO, self).__init__(node_cpp, methods_IO)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 58, in __init__
    setattr(self, m, getattr(node_cpp, m)())
AttributeError: 'torch._C.Value' object has no attribute 'uniqueName'
`
I dont know what was happening

And here is full output:
`/home/rememberoh/anaconda3/envs/HPE/lib/human-pose-estimation.pytorch/pose_estimation/../lib/core/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
=> creating output/mpii/pose_resnet_50/256x256_d256x3_adam_lr1e-3
=> creating log/mpii/pose_resnet_50/256x256_d256x3_adam_lr1e-3_2019-08-13-13-32
Namespace(cfg='experiments/mpii/resnet50/256x256_d256x3_adam_lr1e-3.yaml', frequent=100, gpus=None, workers=None)
{'CUDNN': {'BENCHMARK': True, 'DETERMINISTIC': False, 'ENABLED': True},
 'DATASET': {'DATASET': 'mpii',
             'DATA_FORMAT': 'jpg',
             'FLIP': True,
             'HYBRID_JOINTS_TYPE': '',
             'ROOT': 'data/mpii/',
             'ROT_FACTOR': 30,
             'SCALE_FACTOR': 0.25,
             'SELECT_DATA': False,
             'TEST_SET': 'valid',
             'TRAIN_SET': 'train'},
 'DATA_DIR': '',
 'DEBUG': {'DEBUG': False,
           'SAVE_BATCH_IMAGES_GT': True,
           'SAVE_BATCH_IMAGES_PRED': True,
           'SAVE_HEATMAPS_GT': True,
           'SAVE_HEATMAPS_PRED': True},
 'GPUS': '0',
 'LOG_DIR': 'log',
 'LOSS': {'USE_TARGET_WEIGHT': True},
 'MODEL': {'EXTRA': {'DECONV_WITH_BIAS': False,
                     'FINAL_CONV_KERNEL': 1,
                     'HEATMAP_SIZE': array([64, 64]),
                     'NUM_DECONV_FILTERS': [256, 256, 256],
                     'NUM_DECONV_KERNELS': [4, 4, 4],
                     'NUM_DECONV_LAYERS': 3,
                     'NUM_LAYERS': 50,
                     'SIGMA': 2,
                     'TARGET_TYPE': 'gaussian'},
           'IMAGE_SIZE': array([256, 256]),
           'INIT_WEIGHTS': True,
           'NAME': 'pose_resnet',
           'NUM_JOINTS': 16,
           'PRETRAINED': 'models/pytorch/imagenet/resnet50-19c8e357.pth',
           'STYLE': 'pytorch'},
 'OUTPUT_DIR': 'output',
 'PRINT_FREQ': 100,
 'TEST': {'BATCH_SIZE': 32,
          'BBOX_THRE': 1.0,
          'COCO_BBOX_FILE': '',
          'FLIP_TEST': False,
          'IMAGE_THRE': 0.0,
          'IN_VIS_THRE': 0.0,
          'MODEL_FILE': '',
          'NMS_THRE': 1.0,
          'OKS_THRE': 0.5,
          'POST_PROCESS': True,
          'SHIFT_HEATMAP': True,
          'USE_GT_BBOX': False},
 'TRAIN': {'BATCH_SIZE': 32,
           'BEGIN_EPOCH': 0,
           'CHECKPOINT': '',
           'END_EPOCH': 140,
           'GAMMA1': 0.99,
           'GAMMA2': 0.0,
           'LR': 0.001,
           'LR_FACTOR': 0.1,
           'LR_STEP': [90, 120],
           'MOMENTUM': 0.9,
           'NESTEROV': False,
           'OPTIMIZER': 'adam',
           'RESUME': False,
           'SHUFFLE': True,
           'WD': 0.0001},
 'WORKERS': 4}
=> init deconv weights from normal distribution
=> init 0.weight as normal(0, 0.001)
=> init 0.bias as 0
=> init 1.weight as 1
=> init 1.bias as 0
=> init 3.weight as normal(0, 0.001)
=> init 3.bias as 0
=> init 4.weight as 1
=> init 4.bias as 0
=> init 6.weight as normal(0, 0.001)
=> init 6.bias as 0
=> init 7.weight as 1
=> init 7.bias as 0
=> init final conv weights from normal distribution
=> init 8.weight as normal(0, 0.001)
=> init 8.bias as 0
=> loading pretrained model models/pytorch/imagenet/resnet50-19c8e357.pth
Traceback (most recent call last):
  File "pose_estimation/train.py", line 206, in <module>
    main()
  File "pose_estimation/train.py", line 112, in main
    writer_dict['writer'].add_graph(model, (dump_input, ), verbose=False)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 255, in graph
    list_of_nodes, node_stats = parse(graph, args)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 211, in parse
    nodes_py.append(NodePyIO(node, 'input'))
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 63, in __init__
    super(NodePyIO, self).__init__(node_cpp, methods_IO)
  File "/home/rememberoh/anaconda3/envs/HPE/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 58, in __init__
    setattr(self, m, getattr(node_cpp, m)())
AttributeError: 'torch._C.Value' object has no attribute 'uniqueName'`

**Comment by A465539338** [comment]
I change torch==0.4.1 to torch=1.0.0， there is no such error anymore.

**Comment by jeremyzsq** [comment]
my torch version is 1.2.0,the same error with you

**Comment by cm107** [comment]
This is an error that is being caused by [this commit](https://github.com/pytorch/pytorch/commit/f7b2778cb1db148f1c901ea08abcbfa0e0a78f44#diff-284de3c993add230888834d04a67d666) in pytorch.

In order to fix it, you'll have to make [these changes](https://github.com/lanpa/tensorboardX/commit/9084ab8c41f6aed0719a40abd78bd53c8d9cb793) to venv/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py
