### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#23]
When I try to run the training on COCO, as showed in README.md file, I encountered this error.
```shell
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "pose_estimation/train.py", line 206, in <module>
    main()
  File "pose_estimation/train.py", line 115, in main
    model = torch.nn.DataParallel(model, device_ids=gpus).cuda()
  File "/home/zhouzhou/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/zhouzhou/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/zhouzhou/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/zhouzhou/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/zhouzhou/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74
```

my cuda version is 8.0, my cudnn is 7.2.1, driver version is 381.22

**Comment by Hliang1994** [comment]
@ArchNew I have alse met the same error, and my torch version is 1.0.1. Have you solved this problem?
