### ISSUE TITLE
ModuleNotFoundError: No module named 'nms.gpu_nms'

### ISSUE THREAD

**Issue by Sun0121** [Microsoft/human-pose-estimation.pytorch#44]
Traceback (most recent call last):
  File "pose_estimation/train.py", line 37, in <module>
    import dataset
  File "/home/sunbin/my_project/simple_baselines/human-pose-estimation/pose_estimation/../lib/dataset/__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "/home/sunbin/my_project/simple_baselines/human-pose-estimation/pose_estimation/../lib/dataset/coco.py", line 23, in <module>
    from nms.nms import oks_nms
  File "/home/sunbin/my_project/simple_baselines/human-pose-estimation/pose_estimation/../lib/nms/nms.py", line 14, in <module>
    from .gpu_nms import gpu_nms

**Comment by KaiserLew** [comment]
Hi, you maybe forget executing the **step 5**:
**Make libs:
   cd ${POSE_ROOT}/lib
   make**

**Comment by Sun0121** [comment]
> Hi, you maybe forget executing the **step 5**:
> **Make libs: cd ${POSE_ROOT}/lib make**

Thank you very much. But there still have some problems like this:

Traceback (most recent call last):
  File "pose_estimation/train.py", line 37, in <module>
    import dataset
  File "${POSE_ROOT}/pose_esti                                                                                                             mation/../lib/dataset/__init__.py", line 12, in <module>
    from .coco import COCODataset as coco
  File "${POSE_ROOT}/pose_esti                                                                                                             mation/../lib/dataset/coco.py", line 23, in <module>
    from nms.nms import oks_nms
  File "${POSE_ROOT}/pose_esti                                                                                                             mation/../lib/nms/nms.py", line 13, in <module>
    from .cpu_nms import cpu_nms
**ImportError: ${POSE_ROOT}/pose_estimation/../lib/nms/cpu_nms.so: undefined symbol: _Py_ZeroStruct**

**Comment by leoxiaobin** [comment]
it's usually because that you did not compile the lib correctly.

**Comment by sjtuytc** [comment]
Hi, I meet the same error with you, and I finally solve this by change the Makefile in “lib" directory. More specifically, change "python" to "python3".

> > Hi, you maybe forget executing the **step 5**:
> > **Make libs: cd ${POSE_ROOT}/lib make**
> 
> Thank you very much. But there still have some problems like this:
> 
> Traceback (most recent call last):
> File "pose_estimation/train.py", line 37, in 
> import dataset
> File "${POSE_ROOT}/pose_esti mation/../lib/dataset/**init**.py", line 12, in 
> from .coco import COCODataset as coco
> File "${POSE_ROOT}/pose_esti mation/../lib/dataset/coco.py", line 23, in 
> from nms.nms import oks_nms
> File "${POSE_ROOT}/pose_esti mation/../lib/nms/nms.py", line 13, in 
> from .cpu_nms import cpu_nms
> **ImportError: ${POSE_ROOT}/pose_estimation/../lib/nms/cpu_nms.so: undefined symbol: _Py_ZeroStruct**

**Comment by Sun0121** [comment]
@sjtuytc  Thanks for your advice!

I have solved the problem through your way, and in the Makefile, I find the "python" is system's interpreter. we should change it with ourselves' interpreter path of python

**Comment by Tclz** [comment]
> Hi, I meet the same error with you, and I finally solve this by change the Makefile in “lib" directory. More specifically, change "python" to "python3".
> 
> > > Hi, you maybe forget executing the **step 5**:
> > > **Make libs: cd ${POSE_ROOT}/lib make**
> > 
> > 
> > Thank you very much. But there still have some problems like this:
> > Traceback (most recent call last):
> > File "pose_estimation/train.py", line 37, in
> > import dataset
> > File "${POSE_ROOT}/pose_esti mation/../lib/dataset/**init**.py", line 12, in
> > from .coco import COCODataset as coco
> > File "${POSE_ROOT}/pose_esti mation/../lib/dataset/coco.py", line 23, in
> > from nms.nms import oks_nms
> > File "${POSE_ROOT}/pose_esti mation/../lib/nms/nms.py", line 13, in
> > from .cpu_nms import cpu_nms
> > **ImportError: ${POSE_ROOT}/pose_estimation/../lib/nms/cpu_nms.so: undefined symbol: _Py_ZeroStruct**

Thanks!! I have fixed that follow you said.
